//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameAnalytic
    {
        public int GameId { get; set; }
        public System.DateTime GameStartTime { get; set; }
        public Nullable<System.DateTime> GameEndTime { get; set; }
        public int Player1Id { get; set; }
        public int Player2Id { get; set; }
        public Nullable<int> Player1CookedNum { get; set; }
        public Nullable<int> Player2CookedNum { get; set; }
        public bool WineMenu { get; set; }
        public Nullable<int> TotalTurns { get; set; }
        public bool Quit { get; set; }
        public int Wager { get; set; }
        public bool IsFriendGame { get; set; }
        public bool IsCPUGame { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
