//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PotStirreresDBEntities : DbContext
    {
        public PotStirreresDBEntities()
            : base("name=PotStirreresDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameAnalytic> GameAnalytics { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<LoggedIn> LoggedIns { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PlayerProfile> PlayerProfiles { get; set; }
        public virtual DbSet<GiveawayKey> GiveawayKeys { get; set; }
        public virtual DbSet<DiceSkin> DiceSkins { get; set; }
        public virtual DbSet<User_Dice_Unlock> User_Dice_Unlock { get; set; }
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<IngredientSkin> IngredientSkins { get; set; }
        public virtual DbSet<User_Ingredient_Unlock> User_Ingredient_Unlock { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Chest> Chests { get; set; }
        public virtual DbSet<ChestType> ChestTypes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
    }
}
