//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerProfile
    {
        public string Username { get; set; }
        public Nullable<int> DailyWins { get; set; }
        public Nullable<int> WeeklyWins { get; set; }
        public Nullable<int> AllWins { get; set; }
        public Nullable<int> AllPVPWins { get; set; }
        public int Level { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int Cooked { get; set; }
        public int Stars { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int UserId { get; set; }
        public int Calories { get; set; }
    }
}
